---
title: "subset lines from large files (non-random)"
author: "test"
date: "12/20/2019"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)

### This contains all the data -- total 90.4M rows, 17GB size, 77 monthly files 
rawdatadir = "C:/temp/CitibikeData/"
### This contains 1/1000 of the rows from each of the data files -- total 90.4K rows, 17MB size
slimdatadir = "C:/temp/CitibikeDataSlim/"
```

#### List the names of available citibike data files
```{r list-citibike-data}

rawfilenames=list.files(path=rawdatadir,pattern = 'citibike-tripdata.csv$', full.names = F)    # ending with .csv ; not .zip
length(rawfilenames)
t(t(rawfilenames))

```



```{r getportion}
library(LaF)

getportion <- function(filename, 
                       one_of_n=1000, 
                       inpath="C:/temp/CitibikeData/", 
                       outpath="C:/temp/CitibikeDataSlim/") {
  # one_of_n : choose every "one_of_n" rows from file, where one_of_n is a number like 100 or 1000
  # note: this is deterministic, not random
  infile=paste0(inpath,filename)
  outfile=paste0(outpath,filename)

  # determine number of lines in the file
  nlines=determine_nlines(infile)-1
  print(paste(infile," has ", nlines," rows, after header"))
  # make a (non-random) sequence of line numbers 
  seq_no_header=floor(seq(from=2,to=nlines,length.out = floor(nlines/one_of_n)))
  num_to_get=length(seq_no_header)
  print(paste("Getting ", num_to_get, " rows out of ", nlines))
  seq_with_header=c(1,seq_no_header)
  foo=get_lines(infile,seq_with_header)
  print(paste("writing to ", outfile))
  write_lines(foo,outfile)
}

```


